name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  build:
    runs-on: windows-latest  # Use Windows environment for building

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v2  # Set up Python environment
        with:
          python-version: 3.x  # Specify Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install project dependencies

      - name: Run tests
        run: pytest  # Execute tests using pytest

      - name: Build application
        run: python build.py  # Replace 'build.py' with your build script if needed

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'  # Deploy only on main branch
        run: |
          echo "Deploying to production..."
          # Add deployment commands here
